global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'basic'
    static_configs:
      - targets: [ 'localhost:8080' ]
        metrics_path: '/actuator/prometheus'

  - job_name: 'challenge'
    static_configs:
      - targets: [ 'localhost:8081' ]
    metrics_path: '/actuator/prometheus'

  - job_name: 'vaadin'
    static_configs:
      - targets: [ 'localhost:8082' ]
    metrics_path: '/actuator/prometheus'

  - job_name: 'gwt'
    static_configs:
      - targets: [ 'localhost:8083' ]
    metrics_path: '/actuator/prometheus'
